# -*- coding: utf-8 -*-
"""ExtraEmotions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Pgsphh0GlWdynyBTlhAqJjuy6vC2SSw
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install spotipy

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from spotipy import util
import pandas as pd
import math
import pickle

features_for_mood = ['energy', 'liveness', 'tempo', 'speechiness',
                                     'acousticness', 'instrumentalness', 'danceability', 'duration_ms',
                                     'loudness', 'valence']

def get_track_features(track_ids, spotify):
    chunk_size = 50
    num_chunks = int(math.ceil(len(track_ids) / float(chunk_size)))
    features_add = []
    for i in range(num_chunks):
        chunk_track_ids = track_ids[i * chunk_size:min((i + 1) * chunk_size, len(track_ids))]
        chunk_features = spotify.audio_features(tracks=chunk_track_ids)
        features_add.extend(chunk_features)

    features_df = pd.DataFrame(features_add).drop(['id', 'analysis_url', 'key', 'mode', 'time_signature',
                                                   'track_href', 'type', 'uri'], axis=1)
    features_df = features_df[features_for_mood]
    return features_df

client_credentials_manager = SpotifyClientCredentials(client_id='04ae42a2c0084ab1ae0290a52aa97eea', client_secret='bd4c915259b94f8ebe15d6bf1763b27c')

spotify = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

playlists = {
              'Dark':       ["https://open.spotify.com/playlist/52fjgY5XTdBKrk71TJks1i?si=28df39510a12411e",
                            "https://open.spotify.com/playlist/5xLGNk2Hqi47S1skLPIIZg?si=bb90318b09644f6a"],
             'Energetic' : ["https://open.spotify.com/playlist/4QDWboU5rwpDRXwYprwJf5?si=815ef93592e7475f",
                            "https://open.spotify.com/playlist/0V32mTwWBzo6rNIk21owsY?si=1421ae7c97434fbf"],
             'Relaxing':   ["https://open.spotify.com/playlist/1r4hnyOWexSvylLokn2hUa?si=a622dcb83906450f",
                            "https://open.spotify.com/playlist/11IcIUefRdjIpy1K5GMdOH?si=83b430249c854434"],
             'Aggressive':  ["https://open.spotify.com/playlist/0y1bZzglw6D3t5lPXRmuYS?si=57c0db5e01b9420b",
                             "https://open.spotify.com/playlist/7rthAUYUFcbEeC8NS8Wh42?si=ab7f353f5f2847b3"],
             'Sad':         ["https://open.spotify.com/playlist/2lXXUXSsI8xt7CYxnh7r2O"],
             'Happy' :      ["https://open.spotify.com/playlist/1h90L3LP8kAJ7KGjCV2Xfd?si=5e2691af69e544a3",
                             "https://open.spotify.com/playlist/4AnAUkQNrLKlJCInZGSXRO?si=9846e647548d4026"],
}
tracks = pd.DataFrame()
moods = []
for mood, links in playlists.items():
    print (mood)
    for link in links:
        id = link[34:56]
        try:
            pl_tracks = spotify.playlist_tracks(id)['items']
            ids = [foo['track']['id'] for foo in pl_tracks]
        except:
            print (link)
            continue
        features = get_track_features(ids, spotify)
        features['id'] = ids
        features['mood'] = mood
        tracks = tracks.append(features)

tracks.to_csv('/content/drive/MyDrive/music-mood-classification-main/tracks_6_emo.csv.csv')

import random


#f=open("emo_labels.txt",'r')
# l=[2,2,1,0]


print(l)

d={"Energetic":["gLH_sBM_cAll_d17_mLH4_ch02",
"gLH_sBM_cAll_d18_mLH4_ch02",
"gKR_sBM_cAll_d30_mKR2_ch02",
"gKR_sBM_cAll_d28_mKR2_ch02",
"gBR_sBM_cAll_d04_mBR0_ch02",
"gBR_sBM_cAll_d05_mBR0_ch02",
"gLO_sBM_cAll_d13_mLO2_ch02",
"gLO_sBM_cAll_d15_mLO2_ch02",
"gWA_sBM_cAll_d26_mWA0_ch02",
"gWA_sBM_cAll_d25_mWA0_ch02",
"gMH_sBM_cAll_d24_mMH3_ch02",
"gMH_sBM_cAll_d22_mMH3_ch02",
"gHO_sBM_cAll_d20_mHO5_ch02",
"gHO_sBM_cAll_d21_mHO5_ch02",
"gPO_sBM_cAll_d10_mPO1_ch02",
"gPO_sBM_cAll_d11_mPO1_ch02"],

"Happy":["gBR_sBM_cAll_d04_mBR0_ch02",
"gBR_sBM_cAll_d05_mBR0_ch02",
"gLO_sBM_cAll_d13_mLO2_ch02",
"gLO_sBM_cAll_d15_mLO2_ch02",
"gJB_sBM_cAll_d08_mJB5_ch02",
"gJB_sBM_cAll_d09_mJB5_ch02",
"gJS_sBM_cAll_d03_mJS3_ch02",
"gJS_sBM_cAll_d01_mJS3_ch02",
"gMH_sBM_cAll_d24_mMH3_ch02",
"gMH_sBM_cAll_d22_mMH3_ch02",
"gHO_sBM_cAll_d20_mHO5_ch02",
"gHO_sBM_cAll_d21_mHO5_ch02",
"gPO_sBM_cAll_d10_mPO1_ch02",
"gPO_sBM_cAll_d11_mPO1_ch02"
],

"Aggressive":["gKR_sBM_cAll_d30_mKR2_ch02",
"gKR_sBM_cAll_d28_mKR2_ch02",
"gBR_sBM_cAll_d04_mBR0_ch02",
"gBR_sBM_cAll_d05_mBR0_ch02",
"gLH_sBM_cAll_d17_mLH4_ch02",
"gLH_sBM_cAll_d18_mLH4_ch02"],

"Dark":["gWA_sBM_cAll_d26_mWA0_ch02",
"gWA_sBM_cAll_d25_mWA0_ch02"],

"Sad":["gJB_sBM_cAll_d08_mJB5_ch02",
"gJB_sBM_cAll_d09_mJB5_ch02",
"gJS_sBM_cAll_d03_mJS3_ch02",
"gJS_sBM_cAll_d01_mJS3_ch02"],

"Relaxing":["gJB_sBM_cAll_d08_mJB5_ch02",
"gJB_sBM_cAll_d09_mJB5_ch02",
"gJS_sBM_cAll_d03_mJS3_ch02",
"gJS_sBM_cAll_d01_mJS3_ch02"]}


for i in l:
    print(i)
    if(i==1):
        no = random.randint(1,len(d["Energetic"]))
        print(d["Energetic"][no])
    elif (i==2):
        no = random.randint(1,len(d["Relaxing"]))
        print(d["Relaxing"][no])
    elif(i==3):
        no = random.randint(1,len(d["Dark"]))
        print(d["Dark"][no])
    elif (i==4):
        no = random.randint(1,len(d["Aggressive"]))
        print(d["Aggressive"][no])
    elif(i==5):
        no = random.randint(1,len(d["Sad"]))
        print(d["Sad"][no])
    elif(i==6):
        no = random.randint(1,len(d["Happy"]))
        print(d["Happy"][no])