# -*- coding: utf-8 -*-
"""fact_new

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lCacYumhztECU1KXX_KUxFRgp1J2DL8B
"""

from google.colab import drive
drive.mount('/content/drive')

! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
! chmod +x Miniconda3-py37_4.8.2-Linux-x86_64.sh
! bash ./Miniconda3-py37_4.8.2-Linux-x86_64.sh -b -f -p /usr/local
import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

!conda create -n mint python=3.7
!conda activate mint
!conda install protobuf numpy
!pip install tensorflow absl-py tensorflow-datasets librosa

!sudo apt-get install libopenexr-dev
!pip install --upgrade OpenEXR
#!pip install tensorflow-graphics tensorflow-graphics-gpu

!pip install tensorflow-graphics tensorflow-graphics-gpu

!pip install tensorflow-gpu==2.11.0

!git clone https://github.com/arogozhnikov/einops /tmp/einops
!cd /tmp/einops/ && pip install . -U

!git clone https://github.com/google/aistplusplus_api /tmp/aistplusplus_api
!cd /tmp/aistplusplus_api && pip install -r requirements.txt && pip install . -U

!protoc ./mint/protos/*.proto

!pip install aniposelib

!python /content/drive/MyDrive/Capstone_Project/mint-main/tools/preprocessing.py \
    --anno_dir="/content/drive/MyDrive/Capstone_Project/aistplusplus_api-main/aist_plusplus_final" \
    --audio_dir="/content/drive/MyDrive/Capstone_Project/aistplusplus_api-main/aist_plusplus_final/all_musics" \
    --split=train
!python /content/drive/MyDrive/Capstone_Project/mint-main/tools/preprocessing.py \
    --anno_dir="/content/drive/MyDrive/Capstone_Project/aistplusplus_api-main/aist_plusplus_final" \
    --audio_dir="/content/drive/MyDrive/Capstone_Project/aistplusplus_api-main/aist_plusplus_final/all_musics" \
    --split=testval

#To skip installing everything again
!cp /content/drive/MyDrive/Capstone_Project/Miniconda3-py37_4.8.2-Linux-x86_64.sh /content
!pip install aniposelib

!python /content/drive/MyDrive/Capstone_Project/mint-main/tools/preprocessing1.py

# !pip install einops
# !pip install tensorflow-graphics
!pip install tf-models-official

!python /content/drive/MyDrive/Capstone_Project/mint-main/trainer.py --config_path /content/drive/MyDrive/Capstone_Project/mint-main/configs/fact_v5_deeper_t10_cm12.config --model_dir /content/drive/MyDrive/Capstone_Project/mint-main/checkpoints

!pip install vedo

!pip install chumpy

# caching the generated motions (seed included) to `./outputs`
!python /content/drive/MyDrive/Capstone_Project/mint-main/evaluator.py --config_path /content/drive/MyDrive/Capstone_Project/mint-main/configs/fact_v5_deeper_t10_cm12.config --model_dir /content/drive/MyDrive/Capstone_Project/mint-main/checkpoints2
# calculate FIDs
#!python /content/drive/MyDrive/Capstone_Project/mint-main/tools/calculate_scores.py

!python /content/drive/MyDrive/Capstone_Project/mint-main/tools/preprocessing_approach.py

# calculate FIDs
!python /content/drive/MyDrive/Capstone_Project/mint-main/tools/calculate_scores.py

# !pip install vedo
# !pip install torch
!pip install chumpy

!python /content/drive/MyDrive/Capstone_Project/mint-main/tools/extract_aist_features.py

!ls /content/data/aist_features

!python /content/drive/MyDrive/Capstone_Project/mint-main/tools/preprocessing1.py

!cp /content/Miniconda3-py37_4.8.2-Linux-x86_64.sh /content/drive/MyDrive